# Site wide configuration

title: Genomics and Environmental Research in Microbial Systems
locale: en_US
description: 
logo: site-logo.jpg
search: true
url: http://germslab.org

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Adina Howe
  avatar: bio-photo.jpg
  email: germs.research@gmail.com
  disqus-shortname: 
  twitter: teeniedeenie
  facebook: #username
  github: germs-lab
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-39200706-2
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
